In [2]:
import lmdb
import os
import matplotlib.pyplot as plt
import numpy as np
import zlib
def show_img(img):
    plt.close()
    plt.figure(figsize=(7,7))
    plt.imshow(img)
    plt.show()

In [ ]:
"""
key format:
# first part is position index the second is orientation index 
each frame has 3 keys:
    0000_01_rgb    : 512,512,3 dtype uint8
    0000_01_depth  : 512,512 dtype uint16 depth in mm zero means no depth
    0000_01_pose   : 4x4 float32 c2w matrix
"""

In [3]:
folder = "/work/vig/hieu/3dfront_data/images_renderings"
scene_id = "6a0e73bc-d0c4-4a38-bfb6-e083ce05ebe9"
env = lmdb.open(
    os.path.join(folder, scene_id),
    readonly=True,
    lock=False,
    readahead=False,
    meminit=False,
)
with env.begin() as txn:
    exist_keys = list(txn.cursor().iternext(values=False))
    exist_keys = [key.decode().split('_')[0] for key in exist_keys]

In [ ]:
len(set(exist_keys))

In [ ]:
for i in range(12):
    key = f"0002_{i:0>2}_rgb".encode("ascii")
    txn = env.begin()
    img = zlib.decompress(txn.get(key))
    img = np.frombuffer(img, dtype=np.uint8).reshape(512, 512, 3)
    show_img(img)

In [ ]:
for i in range(12):
    key = f"0000_{i:0>2}_depth".encode("ascii")
    txn = env.begin()
    depth = zlib.decompress(txn.get(key))
    depth = np.frombuffer(depth, dtype=np.uint16).reshape(512, 512)
    show_img(depth)

In [4]:
i = 0
key = f"0000_{i:0>2}_pose".encode("ascii")
txn = env.begin()
pose = zlib.decompress(txn.get(key))
pose = np.frombuffer(pose, dtype=np.float32).reshape(4, 4)
pose

array([[ 1.       ,  0.       ,  0.       , -1.1162988],
       [ 0.       ,  1.       ,  0.       ,  1.5184809],
       [ 0.       ,  0.       ,  1.       , -0.6253474],
       [ 0.       ,  0.       ,  0.       ,  1.       ]], dtype=float32)

In [9]:
import numpy as np
import os

path  = "/media/hieu/T7/3d-front/locations_100/"
# path  = "/media/hieu/T7/3d-front/locations_100_7/"
path  = "/media/hieu/T7/3d-front/poses_100/"
path  = "/media/hieu/T7/3d-front/poses_100_2/"
files = os.listdir(path)
files = [f for f in files if f.endswith(".npy")]
count = []
for x in files:
    data = np.load(os.path.join(path, x))
    count.append(data.shape[0])
max(count), min(count), sum(count), len(count)

(7332, 487, 143861, 99)

In [8]:
(0.7/0.2)**2

12.249999999999996

In [1]:
import numpy as np

a = np.arange(24).reshape(2,3,4)
b = np.arange(36).reshape(3,3,4)
c = np.einsum('nmd,mbd->nmb', a, b)
c.shape

(2, 3, 3)

In [2]:
a,b,c

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]),
 array([[[  14,   38,   62],
         [ 302,  390,  478],
         [ 974, 1126, 1278]],
 
        [[  86,  302,  518],
         [ 950, 1230, 1510],
         [2198, 2542, 2886]]]))

In [3]:
3**0.5

1.7320508075688772