In [1]:
import mathutils
import numpy as np
import quaternion as qt
q = mathutils.Quaternion([0,0,0,1])

In [9]:
q.to_matrix()

Matrix(((-1.0, 0.0, 0.0),
        (0.0, -1.0, 0.0),
        (0.0, 0.0, 1.0)))

In [6]:
mathutils.Matrix.Rotation(np.radians(-90), 4, 'X').to_4x4()

Matrix(((1.0, 0.0, 0.0, 0.0),
        (0.0, -4.371138828673793e-08, 1.0, 0.0),
        (0.0, -1.0, -4.371138828673793e-08, 0.0),
        (0.0, 0.0, 0.0, 1.0)))

In [30]:
def quaternion_to_matrix(args):
    """
    Quaternion to matrix
    :param args:
    :return:
    """
    tx = args[0] + args[0]
    ty = args[1] + args[1]
    tz = args[2] + args[2]
    twx = tx * args[3]
    twy = ty * args[3]
    twz = tz * args[3]
    txx = tx * args[0]
    txy = ty * args[0]
    txz = tz * args[0]
    tyy = ty * args[1]
    tyz = tz * args[1]
    tzz = tz * args[2]

    result = np.zeros((3, 3))
    result[0, 0] = 1.0 - (tyy + tzz)
    result[0, 1] = txy - twz
    result[0, 2] = txz + twy
    result[1, 0] = txy + twz
    result[1, 1] = 1.0 - (txx + tzz)
    result[1, 2] = tyz - twx
    result[2, 0] = txz - twy
    result[2, 1] = tyz + twx
    result[2, 2] = 1.0 - (txx + tyy)
    return result
a2 = quaternion_to_matrix([
                            0,
                            -0.68767,
                            0,
                            0.72602
                        ])
aa2 = qt.from_rotation_matrix(np.array(a2))
v2 = qt.as_rotation_vector(aa2)
print(v2)
# np.degrees(np.linalg.norm(v2)), v2
a2

[-0.          4.76663578 -0.        ]


array([[ 0.05421994, -0.        , -0.99852435],
       [ 0.        ,  1.        , -0.        ],
       [ 0.99852435,  0.        ,  0.05421994]])

In [42]:
a1 = qt.from_float_array([
                            0,
                            -0.38268,
                            0,
                            0.92388
                        ])

a3 = qt.from_float_array([
                            0.92388,
                            0,
                            -0.38268,
                            0,
                        ])
b = qt.as_rotation_matrix(a3)@np.linalg.inv(qt.as_rotation_matrix(a1))
bb = qt.as_euler_angles(qt.from_rotation_matrix(b))
print(bb)
# np.degrees(np.linalg.norm(qt.as_rotation_vector(a1))), qt.as_rotation_vector(a1)
v1 = qt.as_euler_angles(a1)
v3 = qt.as_euler_angles(a3)
v1, v3

[-3.14159265  1.57078293  0.        ]


(array([3.14159265, 0.78539146, 0.        ]),
 array([-3.14159265,  0.78539146,  3.14159265]))

In [40]:
np.degrees(0.78539146)

44.99961592361782

In [7]:
0.70711**2

0.5000045521

In [2]:
import quaternion as qt
import numpy as np
q1 = qt.from_float_array(np.random.rand(4))
q2 = qt.from_float_array(np.random.rand(4))
m = qt.as_rotation_matrix(q1)@qt.as_rotation_matrix(q2)
mm = qt.as_rotation_matrix(q1*q2)
np.allclose(m, mm)

True

In [3]:
isinstance(q1, qt.quaternion)

True

In [3]:
a = np.random.rand(3,3)
a

array([[0.29870781, 0.5951164 , 0.68839697],
       [0.08363247, 0.58214505, 0.24320607],
       [0.52976365, 0.38983003, 0.60057723]])

In [5]:
a[:, [0,2]][[0,2]]

array([[0.29870781, 0.68839697],
       [0.52976365, 0.60057723]])

In [6]:
import os 
model_dir = "/mnt/DATA/personal_projects/BlenderProc-3DFront/examples/datasets/front_3d_with_improved_mat/3D-FUTURE-model"
files = os.listdir(model_dir)

"3120" in files

False

In [8]:
files = sorted(files)
files[-5:]

['fffb8ded-1810-4ac5-bedb-e60444fa4b13',
 'fffd4028-7f01-46c7-96d2-36c3f51b5ba6',
 'ffffcd6c-aadd-44b4-9281-e388fad3c7cc',
 'model_info.json',
 'model_info_revised.json']

In [ ]:
data 